bin = [
  { name = "1", path = "src/1.rs" },
  { name = "2", path = "src/2.rs" },
  { name = "3a", path = "src/3a.rs" },
  { name = "3b", path = "src/3b.rs" },
]

[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
