bin = [
  { name = "1a", path = "src/1a.rs" },
  { name = "1b", path = "src/1b.rs" },
  { name = "2", path = "src/2.rs" },
  { name = "3a", path = "src/3a.rs" },
  { name = "3b", path = "src/3b.rs" },
]

[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
